coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
  precision: 2
  round: down
  range: '70...100'

comment:
  layout: 'header,reach,diff,flags,files,footer'
  behavior: default
  require_changes: true

github_checks:
  annotations: false