[package]
name = "rust-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
lopdf = "0.36.0"
ollama-rs = "0.3.2"
tokio = { version = "1", features = ["full"] }
